### PR TITLE
 test to create corine color table

### PR DESCRIPTION
**Pull request by jehlijos**
test to:

get raster
get GRASS table
create QgsRasterLayer
apply generated table
compare generated table to reference file

### CODE REVIEW

**Review by landam — CHANGES_REQUESTED** [review]
- [x] remove `__pycache__` and update `.gitignore` file
- [x] remove `symbology-style.db` file and update `.gitignore` file
- [x] group imports (built-in first, pyqgis, local as the last)
- [x] all tests pass 

Currently:

```
python3 -m pytest test/test_qgis_color_func.py
```

fails with:

```py
test/test_qgis_color_func.py ....F                                                                         [100%]

==================================================== FAILURES ====================================================
________________________________________________ test_OutputFile _________________________________________________

    def test_OutputFile():
        """
        Check if the output table is created correctly.
        Compare it with reference file.
        """
        # Get the GRASS color table
        GRASStable_path = getCORINEtable()
    
        # Create a temporary qml file
        tempdir = tempfile.mkdtemp()
        Tempfile = os.path.join(tempdir, "tempfile.qml")
    
        # Convert the GRASS color table to QGIS format
        convert_color_table_grass_to_qgis(GRASStable_path, Tempfile)
    
        # Check if the output table is created correctly
        script_dir = Path(__file__).resolve().parent
    
        # Construct the path to the target directory
        target_dir = script_dir.parent / "test" / "reference"
    
        # Specify the filename you want to access
        filename = "corine.qml"
    
        # Create the full path to the file
        CORINE_file_path = target_dir / filename
    
        # Compare the output table with the reference table
        print("Generated file mathces the reference file (corine): ",
              filecmp.cmp(Tempfile, CORINE_file_path, shallow=False))
>       assert filecmp.cmp(Tempfile, CORINE_file_path, shallow=False)
E       AssertionError: assert False
E        +  where False = <function cmp at 0x7f86d95fee80>('/tmp/tmppulo55wu/tempfile.qml', PosixPath('/home/martin/git/ctu-fgis/2024-b-grass-qgis-colors-convert/test/reference/corine.qml'), shallow=False)
E        +    where <function cmp at 0x7f86d95fee80> = filecmp.cmp
```

**Comment by pesekon2** [comment]
> Currently: `python3 -m pytest test/test_qgis_color_func.py` fails

I have checked the test and the fail is caused by the endline symbols. I suppose the reference data were created on Windows, using `^M` for the endline. That's why it fails on our machines. The reference data should be coding-independent

```diff
> diff /tmp/tmpah9sdeis/tempfile.qml /home/pesek/workspace/2024-b-grass-qgis-colors-convert/test/reference/corine.qml | cat -v
1c1
< <!DOCTYPE
---
> <!DOCTYPE^M
```

**Review by pesekon2 — APPROVED** [review]
The tests run correctly now.

**Comment by landam** [comment]
> ```
> python3 -m pytest test/test_qgis_color_func.py
> ```

I may confirm it

**Review by landam — COMMENTED** [review]
In order to close #12 the test should be run in GitHub CI.

**Comment by jehlijos** [comment]
Merging this pr, because as I understand GitHub Action Workflows works with files in master branch.

**Pull request merged**
